### ISSUE TITLE
 i want to do some research on this, could some who upload the ground truth and result  ？

### ISSUE THREAD

**Issue by inviizhy** [CODAIT/deep-histopath#37]
i want to do some research on this, could some who upload the ground truth and result  ？

**Comment by dusenberrymw** [comment]
Hi @inviizhy -- unfortunately, I cannot share the ground truth data, but it can be requested from the [TUPAC16 organizers](http://tupac.tue-image.nl/).

**Comment by inviizhy** [comment]
@dusenberrymw Hi Mike, I have registered at TUPAC16 several days ago, and got the ground truth datas successfully ,I'm learning and rerunning your code. Thank you very much for your kindness .
