### ISSUE TITLE
Unable to import from from tensorflow.python.keras.engine

### ISSUE THREAD

**Issue by bdwyer2** [CODAIT/deep-histopath#40]
[resnet50.py#L30](https://github.com/CODAIT/deep-histopath/blob/master/resnet50.py#L30) errors out with `ModuleNotFoundError: No module named 'tensorflow.python.keras.engine'`

- Linux Mint 18
- Python 3.6.2
- Tensorflow 1.8.0 (CPU version)

Caused by 2bd7c979c5fc1ada90d38f6959839a99f8af4163

**Comment by dusenberrymw** [comment]
@bdwyer2 Yeah I think the `tensorflow.python.keras._impl` was removed in master recently, so I made a change.  Would be good to have a fix that works on both versions.
