### ISSUE TITLE
could you have a version without spark?

### ISSUE THREAD

**Issue by wenhuihuang1979** [CODAIT/deep-histopath#41]
I just have a single GPU workstation, it would be much helpful if you could deprive of spark code from original one.
thanks,

**Comment by feihugis** [comment]
The current code should work on the node with a single GPU. Currently there is no plan for a version without Spark, but you can try [predict_mitoses_help()](https://github.com/CODAIT/deep-histopath/blob/master/deephistopath/inference.py#L233-L378). Hope it can solve your problem.
